### ISSUE TITLE
all files fail for inventory, etc.

### ISSUE THREAD

**Issue by lcerrato** [Capitains/HookTest#148]
Running on local terminal I no longer see any files that pass the following:

URN informations failed
Naming conventions failed
Available in inventory failed

I tried to roll back recent commits because this was working last time I used it for local troubleshooting.

**Comment by sonofmun** [comment]
What was the precise command you used to run the tests locally?

**Comment by lcerrato** [comment]
hooktest -v -c /Users/lcerrato/Development/canonical-greekLit

**Comment by sonofmun** [comment]
Hi @lcerrato. First, I would upgrade to the latest version of hooktest. That is what should be used by Travis as well. In your virtual environment (if you have one), type `pip install -U hooktest`. 
Once this finishes, you should be using the latest version. Then try the following command:
`hooktest -w 3 -s auto -v 5 --console --guidelines 2.epidoc /Users/lcerrato/Development/canonical-greekLit`
You can see what all of these flags mean by simply typing `hooktest` in your terminal. You should then get a short message about them.

**Comment by lcerrato** [comment]
Hi @sonofmun!
I did the upgrade on my terminal.
The upgrade was successful but the command returns an error message of unrecognized arguments for the `--guidelines` and the path itself.
`HookTest-Local: error: unrecognized arguments: --guidelines 2.epidoc /Users/lcerrato/Development/canonical-greekLit`

When I add and subtract things, I just get a set of new unrecognized arguments.
It looks like I cannot add anything after the parameters.

I think this is why I stuck with `hooktest -v -c /Users/lcerrato/Development/canonical-greekLit`— I am sure there must be some local setting issue here.

I am running Python 2.7.10

If it's my setup I'll just close this. I was only using it to avoid checking in changes on student work and it's not worth a ton of troubleshooting.

**Comment by sonofmun** [comment]
I expect the problem is Python 2.7, though I couldn't say that for sure. If you are not averse to installing the newest version of Python (3.7+), then you could set up a virtualenv just to run HookTest. 
Another possible solution is that you could create a branch from the student's branch on Github, make your changes there, then push the your new branch to Github and have Travis run Hooktest on that branch automatically. Then, if everything passes, you could then merge your branch with the student's branch. Or, better yet from a best-practice standpoint, do a PR from your new branch to the student's branch and then have them review it, approve it, and merge it.

**Comment by lcerrato** [comment]
Hi,
I tried a few updates and now just see a syntax error.

I did try to install python3 but I think I have to start over at this point. 

It is easier for most things to just work on the student branches anyhow. I liked to be able to check here and there without committing changes but it's not worth trying to figure out where my system is messed up.

Thanks!
