### ISSUE TITLE
Have URN information where I want to?

### ISSUE THREAD

**Issue by nevenjovanovic** [Capitains/HookTest#48]
The [Guidelines](http://capitains.github.io/pages/guidelines#directory-structure) say "If the text is normal TEI, the convention is to supply the URN the following xpath : `TEI/text/body/@n`." But our texts have `front` and `back` segments that we want to be able to quote, and, moreover, several ill-starred editions sport the `TEI/text/group/text/` structure. How do I tell the hooktest that I want to have the URN at `TEI/text/@n` (so that our files pass that test)?

**Comment by PonteIneptique** [comment]
Could you open the issue on https://github.com/Capitains/Capitains.github.io/issues instead of here ? In fine, it's a guideline issue more than a Hook issue. I have no problems with that. Feel free to make a PR on https://github.com/Capitains/Capitains.github.io/issues to change the guidelines on that point. Then I'll change hooktest.
