### ISSUE TITLE
Hooktest should have an allow_failure parameter

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/HookTest#60]
It would always return 0 in sys exit EXCEPT if there is not even one text.

**Comment by sonofmun** [comment]
I have added this to HookTest. I have also added a step in the hooktest-build to return exit code 1 if manifest.txt has no files in it. These two things are not the same because it is possible that a text could pass but its `__cts__.xml` file does not or vice versa. These two steps should ensure that nothing is deployed if there are no files in the manifest.txt file.

**Comment by sonofmun** [comment]
I still need to test this on Travis to make sure that hooktest-build, as a before_deployment step, will cause deployment not to take place if it fails. The documentation (https://docs.travis-ci.com/user/customizing-the-build/#Deploying-your-Code) says that a failed before_deployment step will lead to an "errored" build which, I assume, will not deploy.

**Comment by sonofmun** [comment]
So this works to return exit code 1 on the before_deployment step. Closing this issue.
